Cherry pick of 81129f9b8d36888a85c5e37089e33e01bc746f2f failed
stdout:
Auto-merging product_replenishment_cost/i18n/es.po
CONFLICT (content): Merge conflict in product_replenishment_cost/i18n/es.po

stderr:
15:23:55.325357 git.c:444               trace: built-in: git cherry-pick 81129f9b8d36888a85c5e37089e33e01bc746f2f
error: could not apply 81129f9b... [FIX]product_replenishment_cost:fixes and improves
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes ingadhoc/product#731

Signed-off-by: Juan José Scarafía <jjs@adhoc.com.ar>
Signed-off-by: Matias Velazquez <mav@adhoc.com.ar>