Cherry pick of aa7eeda4a0d0e66f0a489755d19405eb41ba2f4a failed
stdout:
CONFLICT (add/add): Merge conflict in price_security_replenishment_cost/__manifest__.py
Auto-merging price_security_replenishment_cost/__manifest__.py

stderr:
23:13:56.429352 git.c:444               trace: built-in: git cherry-pick aa7eeda4a0d0e66f0a489755d19405eb41ba2f4a
error: could not apply aa7eeda4... [IMP]price_security_replenishment_cost: new module
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: